/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** The languages supported by Daipendency. */
export const enum Language {
  Rust = 0
}
export interface Symbol {
  name: string
  sourceCode: string
}
export declare class Library {
  static loadDependency(name: string, path: string, language?: Language | undefined | null): Promise<Library>
  static load(path: string, language?: Language | undefined | null): Promise<Library>
  get name(): string
  get version(): string | null
  get documentation(): string
  get language(): Language
  get namespaces(): Array<Namespace>
  generateMarkdownDocumentation(): string
}
export declare class Namespace {
  name: string
  symbols: Array<symbol>
  docComment?: string
}
